ARGV = []
TRUE = true
FALSE = false
STDOUT = IO.new
STDIN = IO.new
STDERR = IO.new
ENV = {}
NIL = nil
RUBY_PATCHLEVEL = 481
RUBY_COPYRIGHT = 'ruby - Copyright (C) 1993-2014 Yukihiro Matsumoto'
TOPLEVEL_BINDING = Binding.new
RUBY_VERSION = '2.0.0'
RUBY_PLATFORM = 'universal.x86_64-darwin14'
